// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clrtaizxwhyacnnfejns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNscnRhaXp4d2h5YWNubmZlam5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjAyNDQsImV4cCI6MjA1OTc5NjI0NH0.y4iQt9rjGIYamUdXQMjlLgOseFGdRhgMDA0Dot-a1gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);